### ISSUE TITLE
Distance Mode transition doesn't seem to be working

### ISSUE THREAD

**Issue by Shimitty** [Zylann/godot_atmosphere_shader#6]
![Errors](https://github.com/Zylann/godot_atmosphere_shader/assets/57539058/2f7dfebb-0e3f-45ee-bded-5180b33902b3)
I'm trying out this addon and found some strange banding when viewed from far away.  I saw a function for avoiding this in the script, but it doesn't seem to be working.  Is there something I'm missing?  Is it because the planet is just a default sphere mesh?  Any assistance is appreciated.

**Comment by Zylann** [comment]
The option doesn't really help that much. In your case I think it might not even make much of a difference since you seem to be using a sphere already for your planet.

Which version of Godot are you using?

**Comment by Shimitty** [comment]
Ok that makes sense.  You're right that I'm using 4.2.  I guess I'll have to disable visibility at long range or wait for Godot 4.3.  planets are slightly on the back burner for me right now so I'll make a plan in the mean time.  Thank you for your quick response.
