### ISSUE TITLE
Strange visual behavior when viewing the atmosphere from a distance

### ISSUE THREAD

**Issue by david4shure** [Zylann/godot_atmosphere_shader#7]
<img width="909" alt="visual_behavior" src="https://github.com/user-attachments/assets/8729234b-6bf5-475f-ad3b-3cd92ef43858">

I am just looking at the default scene, and I see strange behavior when viewing the atmosphere from a distance.

**Comment by Zylann** [comment]
How big is it? How far are you looking at it from? It looks like the distances you're using are simply too large.

**Comment by david4shure** [comment]
Yep, I am not using Godot 4.3 as its curently an RC. The strange behavior seems to be exaggerated on larger objects. I see what you mean about the z-near and z-far. The trouble I am having is that I am trying to make a very large earth that looks nice from far away, and that I can zoom my camera into and look at the sky as if I was on the ground, and to do this well I need to create a sufficiently large earth. Is something like this possible with the current godot version?

> How big is it? How far are you looking at it from? It looks like the distances you're using are simply too large.
> 
> I don't remember seeing that in the default scene 🤔 Which version of Godot is it? Which version of the plugin?
> 
> If you're looking from very far away in Godot 4.2 (in terms of ratio atmosphere height / distance, not absolute distance), it's possible that the depth buffer becomes too imprecise and starts doing this. Having a small near distance or a high far distance in your camera can affect this too. There is a `sphere depth factor` property meant to counteract this effect as you get further and further away, which blends depth to a procedural sphere instead of the depth buffer, though it's not a silver bullet as it might affect how it looks, and might still break at an even higher distance. In the space game I used the plugin into, I also combine that property with a change of near clip distance in camera settings while flying into space, which increases depth precision.
> 
> In Godot 4.3, reverse-Z was implemented and that problem isn't happening. However, it needs a [manual change](https://github.com/Zylann/godot_atmosphere_shader/blob/330cfe9da1f579dab0677027def9ac3e2563a847/addons/zylann.atmosphere/shaders/include/planet_atmosphere_main.gdshaderinc#L20) in the atmosphere shader because Godot didn't expose a `REVERSE_Z` preprocessor symbol, which would have allowed us to handle it automatically...

**Comment by Zylann** [comment]
> Is something like this possible with the current godot version?

Depends what you mean by "current". See what I said.

**Comment by david4shure** [comment]
Thanks for your detailed response Zylann, much appreciated. If I can repro this in the default scene with gotdot 4.3, I will let you know how and give you a project that you can play with that demonstrates this. I think in my original post I scaled it up, without really understanding why it would affect things with the depth buffer / camera z near / far like you explained.

**Comment by david4shure** [comment]
Btw, thank you for building this! Its really awesome work.

**Comment by david4shure** [comment]
Do you know of any learning resources for being more intelligent about how to handle large scales (rather than using a big sphere like I did)?
